title: Open Source Data Science Masters
baseurl: "" # Deploy site at root

# Enable additional functionality
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-minifier
  - jekyll-include-cache

# Exclude development and build artifacts
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Use compressed output for Sass-generated CSS
sass:
  style: compressed

# Minifier plugin options
jekyll-minifier:
  remove_comments: true
  compress_css: true
  compress_javascript: true
  uglifier_args:
    harmony: true

# HTML compression
compress_html:
  clippings: all
  ignore:
    envs: [development]